// <copyright file="PexAssemblyInfo.cs">Copyright ?  2014</copyright>
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using Microsoft.Pex.Framework.Using;
using System.Dynamic;
using Microsoft.Pex.Framework.Suppression;
using Microsoft.CSharp.RuntimeBinder;

[assembly: PexUseType(typeof(DynamicObject))]
[assembly: PexUseType(typeof(ExpandoObject))]
[assembly: PexSuppressUninstrumentedMethodFromType(typeof(CSharpArgumentInfo))]
[assembly: PexSuppressUninstrumentedMethodFromType("System.Runtime.CompilerServices.JitHelpers")]
[assembly: PexSuppressUninstrumentedMethodFromType(typeof(Binder))]
[assembly: PexSuppressUninstrumentedMethodFromType("Microsoft.CSharp.RuntimeBinder.Semantics.SYMTBL+Key")]
